name=RTTTL
version=1.0.0
author=Moony Team
maintainer=Gero Mooslechner
sentence=Library to play RTTTL melodies on a passive buzzer.
paragraph=Provides functions playRtttlBlocking() and playRtttlBlockingPGM().
category=Sound
url=https://github.com/moony-blockly/RTTTL
architectures=*
